In [181]:
import pandas as pd
import sqlite3

# Task 1: Data Gathering and Combination

In [182]:
conn = sqlite3.connect('Library Database.db')

Books=pd.read_sql_query("SELECT * FROM Books",conn)
members=pd.read_sql_query("SELECT * FROM members",conn)
checkouts=pd.read_sql_query("SELECT * FROM checkouts",conn)

Q1_ How much is each member borrowing?

In [183]:
q = """
SELECT
    members.member_id,
    members.first_name,
    members.last_name,
    COUNT(checkouts.checkout_id) AS total_checkouts
FROM members

LEFT JOIN checkouts ON members.member_id = checkouts.member_id
GROUP BY  members.member_id,members.first_name,members.last_name
"""

pd.read_sql_query(q, conn)

    member_id first_name last_name  total_checkouts
0        1001      Salma   Ibrahim                1
1        1002      Fares     Saleh                2
2        1003     Bassel    Hegazy                9
3        1004      Fares     Wahba                0
4        1005    Youssef     Halim                3
..        ...        ...       ...              ...
75       1076       Dina     Wahba                7
76       1077       Lina    Rashad                6
77       1078     Habiba     Osman                0
78       1079       Rana     Osman               10
79       1080     Bassel     Wahba                2

[80 rows x 4 columns]

Q2_Which books match a chosen author pattern?

In [184]:
q="""
select book_id,title,author
from books

where author like 'A%'
"""
pd.read_sql_query(q,conn)

   book_id                title         author
0      501      The Silver Kite  Amina Darwish
1      502       Desert Compass  Amina Darwish
2      503    The Lantern Maker   Adel Roushdy
3      504  Rooftop Astronomers   Adel Roushdy
4      505  Letters to the Nile      Aya Hafez
5      506  The Paper Boat Club      Aya Hafez

Q3_What are the most popular books?

In [185]:
q="""
SELECT
    Books.book_id,
    Books.title,
    COUNT(checkouts.checkout_id) AS total_checkouts
FROM Books

JOIN checkouts ON Books.book_id = checkouts.book_id
GROUP BY Books.book_id , Books.title

order by total_checkouts desc
limit 5
"""
pd.read_sql_query(q,conn)

   book_id                   title  total_checkouts
0      501         The Silver Kite               57
1      507   Fossils and Fireflies               55
2      513  Circuits for Beginners               46
3      519        Kites Over Cairo               38
4      525    Storms and Sailboats               25

Q4_Who are the most active readers?

In [186]:
q="""
SELECT
    members.member_id,
    members.first_name,
    members.last_name,
    COUNT(checkouts.checkout_id) AS total_checkouts
FROM members

JOIN checkouts ON members.member_id = checkouts.member_id
GROUP BY members.member_id,members.first_name,members.last_name

order by total_checkouts desc
limit 10
"""
pd.read_sql_query(q,conn)

   member_id first_name last_name  total_checkouts
0       1034        Aya     Wahba               25
1       1044     Sherif     Saleh               21
2       1008       Ziad     Saleh               19
3       1010       Nour     Nabil               18
4       1027    Mostafa     Fouad               18
5       1018      Ahmed    Shafik               17
6       1024    Youssef    Hegazy               17
7       1065       Adam     Fahmy               17
8       1030       Reem     Osman               16
9       1047       Sara    Rashad               16

Q5_What does a neighborhood's activity look like further back in time?

In [187]:
q="""
SELECT
    checkouts.checkout_date AS checkout_date,
    members.neighborhood,
    checkouts.checkout_id,
    checkouts.return_date,
    checkouts.member_id,
    checkouts.book_id,
    members.first_name,
    members.last_name
FROM members

JOIN checkouts ON members.member_id = checkouts.member_id

where neighborhood = 'Maadi'

order by checkouts.checkout_date DESC
limit 10
offset 10
"""
pd.read_sql_query(q,conn)

,checkout_date,neighborhood,checkout_id,return_date,member_id,book_id,first_name,last_name
0,2025-09-04,Maadi,9103,2025-09-25,1003,513,Bassel,Hegazy
1,2025-08-25,Maadi,9081,2025-09-17,1017,502,Adam,Badr
2,2025-08-23,Maadi,9001,2025-08-28,1008,501,Ziad,Saleh
3,2025-08-21,Maadi,9050,NaN,1003,521,Bassel,Hegazy
4,2025-08-19,Maadi,9085,2025-09-18,1018,525,Ahmed,Shafik
5,2025-08-08,Maadi,9055,2025-08-27,1015,525,Hamza,Sabry
6,2025-08-04,Maadi,9023,2025-08-27,1018,503,Ahmed,Shafik
7,2025-07-27,Maadi,9004,2025-08-16,1013,519,Ziad,Fouad
8,2025-07-22,Maadi,9051,2025-08-18,1003,513,Bassel,Hegazy
9,2025-07-22,Maadi,9010,2025-08-16,1009,513,Hassan,Saleh

In [188]:
conn.close()

combined_data

In [189]:
Books.head()

   book_id                title         author
0      501      The Silver Kite  Amina Darwish
1      502       Desert Compass  Amina Darwish
2      503    The Lantern Maker   Adel Roushdy
3      504  Rooftop Astronomers   Adel Roushdy
4      505  Letters to the Nile      Aya Hafez

In [190]:
members.head()

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05
1,1002,Fares,Saleh,9.0,Maadi,Active,NaN
2,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23
3,1004,Fares,Wahba,7.0,Maadi,inactive,2024-10-09
4,1005,Youssef,Halim,9.0,Maadi,Active,2024-05-05

In [191]:
checkouts.head()

   checkout_id  member_id  book_id checkout_date return_date
0         9263       1047      517    2024-10-21  2024-11-07
1         9340       1072      513    2025-08-24  2025-09-01
2         9231       1053      523    2024-02-04  2024-02-16
3         9129       1032      513    2025-06-21  2025-06-29
4         9370       1079      511    2025-11-11  2025-12-03

In [192]:
book_catalog=pd.read_json('Book Catalog.json')
book_catalog.head()

   book_id       genre  pages  publication_year            publisher
0      501   Adventure    128            2017.0           Nile Press
1      502   Adventure    109            2018.0          Delta House
2      503  Historical    259               NaN           Nile Press
3      504     Science    319            2009.0  Cairo Young Readers
4      505  Historical    216            2024.0          Oasis Books

In [193]:
kickoff=pd.read_html('Reading_Kickoff_Signups.html')
kickoff=kickoff[0]

kickoff.columns=['member_id','book_id','checkout_date']
kickoff.head()

   member_id  book_id checkout_date
0       1026      522    2025-07-11
1       1049      520    2025-07-11
2       1062      525    2025-07-05
3       1065      520    2025-07-07
4       1104      515    2025-07-07

Stage 1

In [194]:
member_counts = checkouts['member_id'].value_counts().reset_index(name='total_books')
member_counts.columns = ['member_id', 'total_books']

In [195]:
stage1 = pd.merge(checkouts, members, on='member_id', how='left')
stage1 = pd.merge(stage1, member_counts, on='member_id', how='left')

Stage 2

In [196]:
full_books = pd.merge(Books, book_catalog, on='book_id', how='left')
stage2 = pd.merge(stage1, full_books, on='book_id', how='left')

Stage 3

In [197]:
kickoff = pd.merge(kickoff, members, on='member_id', how='left')

kickoff = pd.merge(kickoff, full_books, on='book_id', how='left')

kickoff['checkout_id'] = pd.NA
kickoff['return_date'] = pd.NA
kickoff['total_books'] = pd.NA # it will be calculate later

kickoff= kickoff[stage2.columns]

final_df = pd.concat([stage2, kickoff], ignore_index=True)

final_df['total_books'] = (final_df.groupby('member_id')['member_id'].transform('size'))

In [198]:
final_df.shape

(417, 18)

In [199]:
final_df.columns

Index(['checkout_id', 'member_id', 'book_id', 'checkout_date', 'return_date',
       'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status',
       'join_date', 'total_books', 'title', 'author', 'genre', 'pages',
       'publication_year', 'publisher'],
      dtype='str')

In [200]:
final_df.head()

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books,title,author,genre,pages,publication_year,publisher
0,9263,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25,16,Shadows on the Corniche,Hani Nagati,Mystery,338,2015.0,Delta House
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,14,Circuits for Beginners,Galal Mounir,Science,294,2021.0,Oasis Books
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,5,Footsteps in the Dust,Laila Shokry,Historical,276,2018.0,Oasis Books
3,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,6,Circuits for Beginners,Galal Mounir,Science,294,2021.0,Oasis Books
4,9370,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27,10,Winter in Alexandria,Farida Anwar,Historical,117,2016.0,Nile Press

In [201]:
final_df.to_csv("task1_combined_data.csv",index=False)

# Task 2: Data Integrity

In [202]:
df=pd.read_csv('task1_combined_data.csv')

In [203]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 417 entries, 0 to 416
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   checkout_id        391 non-null    float64
 1   member_id          417 non-null    int64
 2   book_id            417 non-null    int64
 3   checkout_date      417 non-null    str
 4   return_date        326 non-null    str
 5   first_name         412 non-null    str
 6   last_name          412 non-null    str
 7   grade              376 non-null    float64
 8   neighborhood       412 non-null    str
 9   membership_status  412 non-null    str
 10  join_date          406 non-null    str
 11  total_books        417 non-null    int64
 12  title              417 non-null    str
 13  author             417 non-null    str
 14  genre              417 non-null    str
 15  pages              417 non-null    int64
 16  publication_year   382 non-null    float64
 17  publisher          417 non-null    str
dtypes: float64(3), int64(4), str(11)
memory usage: 58.8 KB

In [204]:
for i in df.columns:
  if df[i].dtypes == 'float64':
   df[i]=df[i].astype('Int64')

problem 1 : missing value

In [205]:
miss=df.isna().sum()
missing=miss[miss.values>0]
missing

checkout_id          26
return_date          91
first_name            5
last_name             5
grade                41
neighborhood          5
membership_status     5
join_date            11
publication_year     35
dtype: int64

In [206]:
df.isna().sum().sum()

np.int64(224)

In [207]:
mask=df['checkout_id'].isna()

start=df['checkout_id'].max()+1
stop=start+len(df[mask])

df.loc[mask,'checkout_id'] = range(int(start), int(stop))

In [208]:
df['grade']=df['grade'].fillna(df['grade'].mode()[0])

In [209]:
df['publication_year']=df['publication_year'].fillna(df['publication_year'].median())

In [210]:
df['return_date']=df['return_date'].fillna('Unknown')

In [211]:
df['neighborhood']=df['neighborhood'].fillna('Unknown')

In [212]:
df['first_name']=df['first_name'].fillna('Unknown')

In [213]:
df['last_name']=df['last_name'].fillna('Unknown')

In [214]:
df['membership_status']=df['membership_status'].fillna('Unknown')

In [215]:
df['join_date']=df['join_date'].fillna('Unknown')

In [216]:
df.isna().sum()

checkout_id          0
member_id            0
book_id              0
checkout_date        0
return_date          0
first_name           0
last_name            0
grade                0
neighborhood         0
membership_status    0
join_date            0
total_books          0
title                0
author               0
genre                0
pages                0
publication_year     0
publisher            0
dtype: int64

problem 2 : duplicate records

In [218]:
df.duplicated().sum()

np.int64(8)

In [219]:
df[df.duplicated()]

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books,title,author,genre,pages,publication_year,publisher
225,9296,1065,501,2024-12-15,2025-01-11,Adam,Fahmy,6,Zamalek,Active,2025-07-12,18,The Silver Kite,Amina Darwish,Adventure,128,2017,Nile Press
278,9180,1034,529,2024-07-27,2024-08-02,Aya,Wahba,9,Nasr City,Active,2025-01-22,25,Riddles of the Red Sea,Sara Tantawy,Mystery,298,2017,Cairo Young Readers
301,9334,1065,507,2025-12-20,2026-01-05,Adam,Fahmy,6,Zamalek,Active,2025-07-12,18,Fossils and Fireflies,Dalia Serry,Science,160,2024,Nile Press
333,9194,1024,513,2024-09-17,2024-10-09,Youssef,Hegazy,8,Nasr City,inactive,2024-01-04,17,Circuits for Beginners,Galal Mounir,Science,294,2021,Oasis Books
357,9052,1019,501,2024-06-20,2024-06-29,Mostafa,Wahba,6,Maadi,Inactive,2024-07-20,3,The Silver Kite,Amina Darwish,Adventure,128,2017,Nile Press
375,9193,1034,519,2024-09-15,2024-10-01,Aya,Wahba,9,Nasr City,Active,2025-01-22,25,Kites Over Cairo,Jasmine Wahdan,Friendship,157,2014,Nile Press
378,9280,1054,517,2024-09-06,2024-09-15,Retaj,Fahmy,6,Heliopolis,Inactive,2024-03-21,6,Shadows on the Corniche,Hani Nagati,Mystery,338,2015,Delta House
390,9246,1044,529,2025-06-25,2025-07-04,Sherif,Saleh,7,Heliopolis,active,2024-02-19,21,Riddles of the Red Sea,Sara Tantawy,Mystery,298,2017,Cairo Young Readers

In [220]:
df=df.drop_duplicates()

In [221]:
df.duplicated().sum()

np.int64(0)

problem 3 : the same value written diffrent ways

In [222]:
no_Unkown1=df['neighborhood'].value_counts()
no_Unkown1.drop(index='Unknown',inplace=True, errors='ignore')
no_Unkown1

neighborhood
Nasr City     100
Maadi          95
Heliopolis     86
Zamalek        58
Shubra         34
Maadi          19
zamalek        10
NASR CITY       1
HELIOPOLIS      1
Name: count, dtype: int64

In [223]:
df['neighborhood'] = df['neighborhood'].str.title().str.strip()

In [224]:
no_Unkown1=df['neighborhood'].value_counts()
no_Unkown1.drop(index='Unknown',inplace=True, errors='ignore')
no_Unkown1

neighborhood
Maadi         114
Nasr City     101
Heliopolis     87
Zamalek        68
Shubra         34
Name: count, dtype: int64

In [225]:
no_Unkown2=df['membership_status'].value_counts()
no_Unkown2.drop(index='Unknown',inplace=True, errors='ignore')
no_Unkown2

membership_status
Active      275
Inactive     53
active       45
inactive     31
Name: count, dtype: int64

In [226]:
df['membership_status'] = df['membership_status'].str.title().str.strip()

In [227]:
no_Unkown2=df['membership_status'].value_counts()
no_Unkown2.drop(index='Unknown',inplace=True, errors='ignore')
no_Unkown2

membership_status
Active      320
Inactive     84
Name: count, dtype: int64

problem 4: checkouts with no matching member

In [228]:
registered_ids = members['member_id'].unique()

unregistered_ids = df[~df['member_id'].isin(registered_ids)]

unregistered_ids

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books,title,author,genre,pages,publication_year,publisher
395,9388,1104,515,2025-07-07,Unknown,Unknown,Unknown,9,Unknown,Unknown,Unknown,2,Songs of the Oasis,Hoda Bakry,Poetry,316,2022,Cairo Young Readers
400,9393,1201,509,2025-07-10,Unknown,Unknown,Unknown,9,Unknown,Unknown,Unknown,2,Marbles and Mirrors,Diaa Sultan,Mystery,221,2011,Nile Press
402,9395,1104,526,2025-07-05,Unknown,Unknown,Unknown,9,Unknown,Unknown,Unknown,2,The Clockwork Orchard,Mahmoud Rafei,Science Fiction,125,2016,Delta House
405,9398,1150,530,2025-07-10,Unknown,Unknown,Unknown,9,Unknown,Unknown,Unknown,1,The Sandstone Key,Sara Tantawy,Adventure,208,2012,Oasis Books
415,9408,1201,523,2025-07-08,Unknown,Unknown,Unknown,9,Unknown,Unknown,Unknown,2,Footsteps in the Dust,Laila Shokry,Historical,276,2018,Oasis Books

In [229]:
unregistered_ids['member_id']

395    1104
400    1201
402    1104
405    1150
415    1201
Name: member_id, dtype: int64

In [230]:
unregistered_ids['member_id'].value_counts()

member_id
1104    2
1201    2
1150    1
Name: count, dtype: int64

save

In [231]:
df.to_csv("task2_cleaned_data.csv",index=False)

# Task 3: Data Fairness and Version Control

In [232]:
df=pd.read_csv('task2_cleaned_data.csv')

In [233]:
df.shape

(409, 18)

In [234]:
df.head()

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books,title,author,genre,pages,publication_year,publisher
0,9263,1047,517,2024-10-21,2024-11-07,Sara,Rashad,9,Heliopolis,Inactive,2024-06-25,16,Shadows on the Corniche,Hani Nagati,Mystery,338,2015,Delta House
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9,Zamalek,Active,2025-10-21,14,Circuits for Beginners,Galal Mounir,Science,294,2021,Oasis Books
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9,Heliopolis,Active,2024-01-03,5,Footsteps in the Dust,Laila Shokry,Historical,276,2018,Oasis Books
3,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7,Nasr City,Active,2025-10-19,6,Circuits for Beginners,Galal Mounir,Science,294,2021,Oasis Books
4,9370,1079,511,2025-11-11,2025-12-03,Rana,Osman,8,Shubra,Active,2024-10-27,10,Winter in Alexandria,Farida Anwar,Historical,117,2016,Nile Press

In [235]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   checkout_id        409 non-null    int64
 1   member_id          409 non-null    int64
 2   book_id            409 non-null    int64
 3   checkout_date      409 non-null    str
 4   return_date        409 non-null    str
 5   first_name         409 non-null    str
 6   last_name          409 non-null    str
 7   grade              409 non-null    int64
 8   neighborhood       409 non-null    str
 9   membership_status  409 non-null    str
 10  join_date          409 non-null    str
 11  total_books        409 non-null    int64
 12  title              409 non-null    str
 13  author             409 non-null    str
 14  genre              409 non-null    str
 15  pages              409 non-null    int64
 16  publication_year   409 non-null    int64
 17  publisher          409 non-null    str
dtypes: int64(7), str(11)
memory usage: 57.6 KB

Data Fairness

In [236]:
result=df.groupby('neighborhood').agg(
    number_of_members= ('member_id','nunique'),
    number_of_checkouts= ('checkout_id','count'))

In [237]:
result['checkouts_per_member'] = (result['number_of_checkouts'] / result['number_of_members']).round(2)

In [238]:
result=result.drop(index='Unknown',axis=0, errors='ignore')
sort_result=result.sort_values(by='checkouts_per_member')
sort_result

              number_of_members  number_of_checkouts  checkouts_per_member
neighborhood
Maadi                        20                  114                  5.70
Zamalek                      11                   68                  6.18
Nasr City                    16                  101                  6.31
Heliopolis                   13                   87                  6.69
Shubra                        5                   34                  6.80